server:
  port: 8081

spring:
  application:
    name: product-api
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:mysql://localhost:3306/productdb}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    tags:
      application: product-api
